services:
  w_db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

  weather:
    restart: always
    build: .
    #    command: python manage.py runserver 0.0.0.0:8000
    #    command: gunicorn -b 0.0.0.0:8000 voditel.wsgi:application
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 main.wsgi:application"
    env_file:
      - .env
    depends_on:
      - w_db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  w_nginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - weather
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
  db_volume:
